// ============================================================
// admin-api Edge Function
//
// Why this exists: creating a login for a new patient, and
// resetting a patient's password, both require Supabase's
// SERVICE ROLE key — a secret that must never appear in the
// website's own code (GitHub Pages is public, so anything in
// the site's JS is visible to anyone). This function runs on
// Supabase's servers instead, keeps that secret there, and only
// does its work after checking the person calling it is really
// the logged-in admin.
//
// Deploy with:  supabase functions deploy admin-api
// (SUPABASE_URL / SUPABASE_ANON_KEY / SUPABASE_SERVICE_ROLE_KEY
//  are provided automatically by Supabase — nothing to set up.)
// ============================================================

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function randomTempPassword() {
  // e.g. "Ctk-7f3q9k2a" — easy to read aloud over the phone
  const chars = "abcdefghjkmnpqrstuvwxyz23456789";
  let s = "";
  for (let i = 0; i < 10; i++) s += chars[Math.floor(Math.random() * chars.length)];
  return "Ctk-" + s;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });

  try {
    const authHeader = req.headers.get("Authorization") || "";
    const callerToken = authHeader.replace("Bearer ", "");
    if (!callerToken) throw new Error("Not logged in.");

    // Client that acts AS the caller, to check who they are
    const callerClient = createClient(SUPABASE_URL, ANON_KEY, {
      global: { headers: { Authorization: `Bearer ${callerToken}` } },
    });
    const { data: userData, error: userErr } = await callerClient.auth.getUser();
    if (userErr || !userData?.user) throw new Error("Could not verify caller.");

    // Admin client, only used AFTER we've confirmed the caller is an admin
    const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

    const { data: profile } = await admin
      .from("profiles")
      .select("role")
      .eq("id", userData.user.id)
      .single();

    if (!profile || profile.role !== "admin") {
      return new Response(JSON.stringify({ error: "Admin access required." }), {
        status: 403,
        headers: { ...cors, "Content-Type": "application/json" },
      });
    }

    const body = await req.json();
    const action = body.action;

    // ----------------------------------------------------------
    // Admin adds a brand-new patient and creates their login
    // ----------------------------------------------------------
    if (action === "create_patient") {
      const { full_name, age, sex, phone, email, patient_code } = body;
      if (!full_name || !phone) throw new Error("Name and phone are required.");

      const tempPassword = randomTempPassword();
      // Patients always log in with their phone number. This is the account's
      // auth identifier; any real email given is stored separately, contact-only.
      const loginEmail = `${phone.replace(/\D/g, "")}@patients.carditek.local`;

      const { data: created, error: createErr } = await admin.auth.admin.createUser({
        email: loginEmail,
        password: tempPassword,
        email_confirm: true,
        user_metadata: { role: "patient" },
      });
      if (createErr) throw createErr;

      // the trigger in schema.sql already made a profiles row; mark must-change-password
      await admin.from("profiles").update({ must_change_password: true }).eq("id", created.user.id);

      const { error: patientErr } = await admin.from("patients").insert({
        id: created.user.id,
        patient_code: patient_code || null, // null = auto-generated by the DB trigger
        full_name, age, sex, phone,
        email: email || null,
        consent_given: false,
      });
      if (patientErr) throw patientErr;

      return new Response(JSON.stringify({
        login_email: loginEmail,
        temp_password: tempPassword,
      }), { headers: { ...cors, "Content-Type": "application/json" } });
    }

    // ----------------------------------------------------------
    // Admin resets an existing patient's password (phone support)
    // ----------------------------------------------------------
    if (action === "reset_password") {
      const { patient_id } = body;
      if (!patient_id) throw new Error("patient_id is required.");

      const tempPassword = randomTempPassword();
      const { error: pwErr } = await admin.auth.admin.updateUserById(patient_id, {
        password: tempPassword,
      });
      if (pwErr) throw pwErr;

      await admin.from("profiles").update({ must_change_password: true }).eq("id", patient_id);

      return new Response(JSON.stringify({ temp_password: tempPassword }), {
        headers: { ...cors, "Content-Type": "application/json" },
      });
    }

    throw new Error("Unknown action.");
  } catch (err) {
    return new Response(JSON.stringify({ error: err.message || String(err) }), {
      status: 400,
      headers: { ...cors, "Content-Type": "application/json" },
    });
  }
});
